services:
  - type: web
    name: exhibition-voice-logger-backend
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8080
      - key: TARGET_DRIVE_FOLDER_ID
        value: 1aaD44uttnMpWdLo19tko-8Ipl3_MUhbk
      - key: GOOGLE_APPS_SCRIPT_URL
        value: https://script.google.com/macros/s/AKfycbwzV4dCMkXfNYM2bxGHMe1l_I5n72-GMfccyAuyoEhSq_cYGnhVjU3Ql-PNOxStNyEs/exec
      - key: NIM_SERVER_URL
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
